<?php

namespace DNAToolkit\Tests\Extractors;

use DNAToolkit\Extractors\Plain;
use PHPUnit\Framework\TestCase;

/**
 * @group Extractors
 * @covers \DNAToolkit\Extractors\Plain
 */
class PlainTest extends TestCase
{
    /**
     * @var \DNAToolkit\Extractors\Plain
     */
    protected $extractor;

    /**
     * @before
     */
    protected function setUp() : void
    {
        $this->extractor = new Plain('tests/test.plain');
    }

    /**
     * @test
     */
    public function extract() : void
    {
        $expected = [
            'TGAGCATTCCCGATATGGTTCTCATTCATGCAGGCACTAATGATATGTTGCAAAACTATTCCGTCAATCATGCTGTAGATCATATTCGAGAAACGATTGATGTGCTACGCCAAAGAAATCCAAATACAGATTGGCAATTACATGAATTTCGCAGGTATCTCAAAAAAAATGGATACCCAAATCATGCAAATACGTTAATGGATTTATGGAAAAATCCATATCAATCAAACGCAAAAGAAA',
            'TATCCAAGTGATTTACATGCAGATCTCATATAGCAAAGATGTTAAATAATACAAAAAATAACCACTTTTCATCGTATCAATATAGGTCCGTCAAGACAATTTTGAAATATTGATGCTACGGATTTATATGTTTTAATATTCTTTTAAGGAAAGTCTGCGGGAGTCCTTGAGGTAGAAAATTGAAATTATTTTGAGGAGAAAAAGAATTTTGAACGAAGGAGTTTTGCCGTAGTAAAGGGA',
            'AAGAAAAGTTTTCAATTCTTAGTGCAATAAATGCTCATACCAAAATTCTTTTTTTTAATTAAGCTGATCAATTTTTACAAAAAACAACATCGAATGTCAACATCTTTTTCTCCAATTAGAAAAAACAATCATCACCAGCTAACGTCATAATCGGTTTCGACATTTTTGACATATGAACTTTAAAGGTGATACCCTTTAGATACTCAGTTTATACTAAAAATAACAACCTTATATCTATAA',
        ];

        $reads = iterator_to_array($this->extractor);

        $this->assertEquals($expected, $reads);
    }
}
